defaults:
  - _self_
  - model: qwen_7b
  - attention: dense
  - task: ruler_niah

mode: "all"
overwrite: false
debug: false

gpus: 1
tp: 1

samples: 100
max_input_tokens: 8192
max_output_tokens: 1024
kv_cache_block_size: 256
random_seed: 43

print_eval_results: true

paths:
  results: ./experiments/results
  predictions: ./experiments/predictions
  data: ./experiments/data
  debug: ./experiments/debug
  checkpoints: ./experiments/checkpoints

hydra:
  run:
    dir: ./experiments/hydraoutputs/${now:%Y-%m-%d_%H-%M-%S}
  job:
    env_set:
      OMP_NUM_THREADS: 1
